### PR TITLE
Add support for bgr24 format

### PR DESCRIPTION
**Pull request by romainreignier**
It then send the image message directly in "bgr8" because it is supported by ROS and it is the native OpenCV format, so less processing will be needed.

This format is supported by Raspberry Pi V4L2 driver.

### CODE REVIEW

**Comment by flynneva** [comment]
hey @romainreignier! great contribution!!! would you be willing to make this PR over on the ros2 branch as well? I have recently taken over maintenance for the ros2 version of this package and would love to get these types of enhancements included going forward.

**Comment by romainreignier** [comment]
Hi @flynneva 
I am ok to try to implement it on the ros2 version, but I am not home these days so I have nothing to try it.
If I forget, feel free to remind me or implement it yourself.

**Comment by flynneva** [comment]
@romainreignier for me this package works for my laptops built-in webcam as well! So that's what I've been testing it with. If you have a laptop with a built-in webcam it might work for you too?

**Comment by twdragon** [comment]
@romainreignier @flynneva taking PR into consideration

**Pull request closed without merging**
