### PR TITLE
fix timestamp issue and use v4l2  for brightness, contrast, saturation, sharpness, gain…

### PR DESCRIPTION
**Pull request by johnjamesmiller**
auto_white_balance, white_balance, autoexposure, exposure, autofocus, focus

### CODE REVIEW

**Comment by flynneva** [comment]
@johnjamesmiller thanks so much for this awesome contribution! The changes look good to me at first glance, just need to fix the linter errors.

**Comment by johnjamesmiller** [comment]
Happy to help! Is there a vscode extension or auto formatter that you
recommend?

**Comment by flynneva** [comment]
@johnjamesmiller the CI is running the typical ament_* linters (uncrustify, cpplint and flake8 for python).

I'd suggest just using those. They should come with any of the ROS 2 distros, just source /opt/ros/<distro>/setup.bash and run the directly in the top-level usb_cam directory via CLI by calling them by name:

$ ament_uncrustify
$ ament_cpplint

**Comment by johnjamesmiller** [comment]
@flynneva  I think I've got the linting sorted can you give it another go? Thanks!

**Comment by flynneva** [comment]
@johnjamesmiller sounds good, running CI again.

**Review by flynneva — APPROVED** [review]

**Comment by flynneva** [comment]
@johnjamesmiller thanks again for the contribution! Sorry it took so long for me to get around to approving it 😅

**Pull request merged**
