### PR TITLE
Bouncy version

### PR DESCRIPTION
**Pull request by lucasw**
I haven't touched this (or ros2) in a while, but it should be a reasonable starting point.  A few things would be nice to see ported over to a noetic branch.

Looking at the number commits now it looks like an aggressive rebase -i would be good to squash this down.

Begins to address #103

### CODE REVIEW

**Comment by Karsten1987** [comment]
thanks for getting things started here. Do you mind if we tackle the most recent ros2 version instead of bouncy? I feel like we should either get a version merged which is compliant with Foxy or ROS2 master.

**Comment by flynneva** [comment]
i just made a PR to @lucasw's bouncy branch with minor updates to get it functioning for foxy. tested on a usb camera and I can confirm it is functioning.

**Comment by flynneva** [comment]
@lucasw , now that ive got maintainer status for this repo - want to go ahead and do your `rebase -i` to clean up these commits?

if you're too busy, just let me know and I can close this PR then and incorporate the changes in the foxy PR ive got open #132

**Comment by lucasw** [comment]
> if you're too busy, just let me know and I can close this PR then and incorporate the changes in the foxy PR ive got open #132

Yes close this and go with #132 (but please do squash that down)

**Pull request closed without merging**
