### PR TITLE
add ROS Orphaned Package Maintainers to maintainer tag

### PR DESCRIPTION
**Pull request by k-okada**
@rctoris I'm willing to release this repository in to kinetic/lunar on behalf of unmaintaned package maintaner groups, before releasing this repoistory we need to add new version and tags, if you do not have time to do that, could you give write permission to @k-okada ? 

c.f https://discourse.ros.org/t/releasing-repositories-form-other-people/1797

### CODE REVIEW

**Comment by k-okada** [comment]
Also we need access to https://github.com/bosch-ros-pkg-release/usb_cam-release

**Comment by rctoris** [comment]
@k-okada I think the best thing to do at this point is to fork to project and GBP as either an orphaned un-maintained package or with a new maintainer if someone is willing. I am no longer associated with Bosch and cannot grant write access to their repositories at this point and unfortunately do not know who to contact in order to get that. I could also put a message on the repo stating where the project has moved to.

**Comment by dirk-thomas** [comment]
@chaoflow @flixr @iluetkeb @KaijenHsiao @NikolausDemmel @proan @sosentos Can any of the other owner of this org unit comment if they are willing to move the repository to a ros org unit instead since it seems to be abandoned?

**Comment by Karsten1987** [comment]
cc @MatthiasRoland  @maxriz

**Comment by NikolausDemmel** [comment]
Yes, IMHO we should move it.

**Comment by k-okada** [comment]
@dirk-thomas so, can we move the repo?

**Comment by dirk-thomas** [comment]
I don't know anybody who has access for this repo. So you will have to fork it.

**Comment by KaijenHsiao** [comment]
@lorenzoriano

**Comment by NikolausDemmel** [comment]
I can move it. What do I have to do?

**Comment by NikolausDemmel** [comment]
I.e. where exactly should this be moved and the release repo?

**Comment by k-okada** [comment]
thanks, may be https://github.com/ros-drivers ? and usb_cam-release to https://github.com/ros-gbp ?

**Comment by NikolausDemmel** [comment]
Alright. Waiting on confirmation from @dirk-thomas

**Comment by dirk-thomas** [comment]
> may be https://github.com/ros-drivers ? and usb_cam-release to https://github.com/ros-gbp ?

Sounds good.

**Comment by lorenzoriano** [comment]
Yup @NikolausDemmel please transfer it to the new organization. It's quite easy once you have the permission. Please let me know if you need assistance

**Comment by NikolausDemmel** [comment]
I tried to do the transfer of this repo, but I got an error saying "You don’t have the permission to create repositories on ros-drivers". Not sure if that triggered a notification for ros-drivers Owners to confirm the transfer.

Also, I noticed that the release repo is in another organization, which I cannot access. @rctoris, you are the only one listed under "people" for https://github.com/bosch-ros-pkg-release. Could you maybe give ownership to that organization to the owners of bosch-ros-pkg?

**Comment by rctoris** [comment]
I also tried to move the repo but I don't have access to ros-gbp

**Comment by k-okada** [comment]
@rctoris @NikolausDemmel thank you for your effort, may be you have to add @dirk-thomas to your organization and ask them to move the repo, or ask @dirk-thomas to include @rctoris @NikolausDemmel to ros-drivers and ros-gbp

**Comment by NikolausDemmel** [comment]
Jup, it seems according to https://help.github.com/articles/transferring-a-repository-owned-by-your-organization/ that I would need "repository creation rights" on the receiving organization. The option that the receiver gets an email to confirm seems only available for transferring to another user account, not organization.

By now I have rights also to the release org, so I  could do the transfer of both repos.

**Comment by dirk-thomas** [comment]
@NikolausDemmel I added you temporarily to both org unit. Please let me know once you have moved the repos.

**Comment by NikolausDemmel** [comment]
@dirk-thomas I transfered the release repo to ros-gbp, but you gave me access to `ros`, not `ros-drivers`. Should I transfer to `ros`, else please give me access to `ros-drivers`.

P.S.: When asked which teams to give access for the release repo, I only added `Owners`, so you might need to sort out permissions as needed.

**Comment by dirk-thomas** [comment]
@NikolausDemmel Sorry, fixed. I will create a team and add @k-okada to it and let him add more people.

**Comment by NikolausDemmel** [comment]
It is done. As teams I again added only "Core Team".

**Comment by dirk-thomas** [comment]
@NikolausDemmel Thanks for transferring the repos.

@k-okada You are now a collaborator on both repos with the *admin* role. So you can add other people to the repo as well. Please take it from here,

**Comment by k-okada** [comment]
@dirk-thomas @NikolausDemmel Thank you all, finally released in to kinetic!!!! -> https://github.com/ros/rosdistro/pull/15225

**Pull request merged**
