### PR TITLE
Various cleanups for the ROS 2 branch

### PR DESCRIPTION
**Pull request by clalancette**
While trying to build this package against the latest Rolling sources, I ran into a number of warnings.  This PR fixes some of them.  The rest of the warnings are about the use of deprecated FFMPEG functions, which will need a deeper look to fix.

### CODE REVIEW

**Comment by clalancette** [comment]
CI is failing on rolling because image_transport_plugins isn't currently building on the ROS 2 buildfarm: https://build.ros2.org/job/Rbin_uJ64__image_transport_plugins__ubuntu_jammy_amd64__binary/ .  Once that is resolved, CI should be able to proceed here.

**Comment by clalancette** [comment]
And CI is now happy here, so I think we can proceed.

**Comment by clalancette** [comment]
Fantastic, thanks for merging!  Would you mind doing a new release into Rolling?

**Comment by flynneva** [comment]
@clalancette sure! Give me a few days to find some time

**Comment by clalancette** [comment]
> @clalancette here is [the open PR to `rosdistro`](https://github.com/ros/rosdistro/pull/32893) for this package for `rolling`. I'll make another one for `humble` as well too

Thanks, appreciated!

**Pull request merged**
