### PR TITLE
Add separate relative and private node handles

### PR DESCRIPTION
**Pull request by jacobperron**
Private node handle for parameters.
Relative node handle for topics / services.
Addresses issue #42.

### CODE REVIEW

**Comment by rctoris** [comment]
This will likely break a vast majority of peoples running projects as their default topic names will change without them knowing why.

**Comment by jacobperron** [comment]
Perhaps there could be an option in the next release to use to use the fix (default: off), but with a warning that it will be changed in a future release?

**Comment by jacobperron** [comment]
@rctoris I can implement the workaround I mentioned (adding a temporary parameter `use_private_nh`, by default `false`), or another solution if you have a better idea. Let me know.

**Comment by jacobperron** [comment]
Since this is an API breaking change, incorporating it as part of a Melodic release seems like a good candidate :wink:

**Comment by twdragon** [comment]
As the proposed changes may be considered API breaking for users running the node and the workaround is obvious via [`roslaunch` XML](http://wiki.ros.org/roslaunch/XML), and also due to 5 years of inactivity, the PR is closed as API breaking proposal.

**Pull request closed without merging**
