### PR TITLE
Fix mjpeg invalid ptr and mjpeg memory leak

### LINKED ISSUE #274: invalid pointer
[INFO] [launch]: All log files can be found below /home/vis/.ros/log/2023-08-15-21-27-35-910267-vis-Z590-D-95045
[INFO] [launch]: Default logging verbosity is set to INFO
/home/vis/Desktop/cam/install/usb_cam/share/usb_cam/config/params_1.yaml
[INFO] [usb_cam_node_exe-1]: process started with pid [95046]
[INFO] [show_image.py-2]: process started with pid [95048]
[usb_cam_node_exe-1] [INFO] [1692120456.064841763] [usb_cam]: camera_name value: test_camera
[usb_cam_node_exe-1] [WARN] [1692120456.064921117] [usb_cam]: framerate: 30.000000
[usb_cam_node_exe-1] [INFO] [1692120456.065972218] [usb_cam]: camera calibration URL: package://usb_cam/config/camera_info.yaml
[usb_cam_node_exe-1] [INFO] [1692120456.066341856] [usb_cam]: Starting 'test_camera' (/dev/video0) at 1920x1080 via mmap (mjpeg2rgb) at 30 FPS
[usb_cam_node_exe-1] [INFO] [1692120456.182394506] [usb_cam]: This devices supproted formats:
[usb_cam_node_exe-1] [INFO] [1692120456.182518988] [usb_cam]: 	Motion-JPEG: 1920 x 1080 (60 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182526842] [usb_cam]: 	Motion-JPEG: 1920 x 1080 (60 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182530764] [usb_cam]: 	Motion-JPEG: 1280 x 720 (60 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182534342] [usb_cam]: 	Motion-JPEG: 960 x 540 (60 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182537549] [usb_cam]: 	Motion-JPEG: 640 x 360 (60 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182540552] [usb_cam]: 	Motion-JPEG: 640 x 480 (54 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182543538] [usb_cam]: 	Motion-JPEG: 800 x 600 (54 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182546908] [usb_cam]: 	Motion-JPEG: 1024 x 768 (54 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182549867] [usb_cam]: 	Motion-JPEG: 1280 x 960 (54 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182552914] [usb_cam]: 	Motion-JPEG: 1600 x 1200 (54 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182586956] [usb_cam]: 	Motion-JPEG: 1920 x 1080 (60 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182590304] [usb_cam]: 	Motion-JPEG: 1920 x 1080 (60 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182593376] [usb_cam]: 	YUYV 4:2:2: 1920 x 1080 (60 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182596436] [usb_cam]: 	YUYV 4:2:2: 1920 x 1080 (60 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182599559] [usb_cam]: 	YUYV 4:2:2: 1280 x 720 (60 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182602748] [usb_cam]: 	YUYV 4:2:2: 960 x 540 (60 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182605950] [usb_cam]: 	YUYV 4:2:2: 640 x 360 (60 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182609058] [usb_cam]: 	YUYV 4:2:2: 640 x 480 (54 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182612126] [usb_cam]: 	YUYV 4:2:2: 800 x 600 (54 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182615183] [usb_cam]: 	YUYV 4:2:2: 1024 x 768 (54 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182618240] [usb_cam]: 	YUYV 4:2:2: 1280 x 960 (54 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182621258] [usb_cam]: 	YUYV 4:2:2: 1600 x 1200 (54 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182624468] [usb_cam]: 	YUYV 4:2:2: 1920 x 1080 (60 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182627711] [usb_cam]: 	YUYV 4:2:2: 1920 x 1080 (60 Hz)
[usb_cam_node_exe-1] unknown control 'white_balance_temperature_auto'
[usb_cam_node_exe-1] 
[usb_cam_node_exe-1] [INFO] [1692120456.184186976] [usb_cam]: Setting 'white_balance_temperature_auto' to 1
[usb_cam_node_exe-1] [INFO] [1692120456.184205567] [usb_cam]: Setting 'exposure_auto' to 3
[usb_cam_node_exe-1] unknown control 'exposure_auto'
[usb_cam_node_exe-1] 
[usb_cam_node_exe-1] [INFO] [1692120456.185539165] [usb_cam]: Setting 'focus_auto' to 0
[usb_cam_node_exe-1] unknown control 'focus_auto'
[usb_cam_node_exe-1] 
[usb_cam_node_exe-1] [INFO] [1692120456.188846173] [usb_cam]: Timer triggering every 33 ms
[usb_cam_node_exe-1] free(): invalid pointer
[ERROR] [usb_cam_node_exe-1]: process has died [pid 95046, exit code -6, cmd '/home/vis/Desktop/cam/install/usb_cam/lib/usb_cam/usb_cam_node_exe --ros-args -r __node:=usb_cam --params-file /home/vis/Desktop/cam/install/usb_cam/share/usb_cam/config/params_1.yaml'].

I compiled this command 
ros2 launch usb_cam demo_launch.py

### LINKED ISSUE #275: invalid pointer (camera can be started with VLC)
### Description

Basically just clone it, and tried the simplest setup to try to view the image. Unfortunately, error being thrown out...

```
$ ros2 run usb_cam usb_cam_node_exe --ros-args --params-file /home/thomas/Development/usb_cam/config/params_2.yaml 
[INFO] [1692153315.491018936] [usb_cam]: camera_name value: usb_cam
[WARN] [1692153315.491127087] [usb_cam]: framerate: 30.000000
[INFO] [1692153315.498681813] [usb_cam]: camera calibration URL: package://usb_cam/config/camera_info.yaml
[WARN] [1692153315.500304206] [usb_cam]: [usb_cam] does not match test_camera in file /home/thomas/Development/usb_cam/install/usb_cam/share/usb_cam/config/camera_info.yaml
[INFO] [1692153315.500354095] [usb_cam]: Starting 'usb_cam' (/dev/video2) at 640x480 via mmap (mjpeg2rgb) at 30 FPS
[INFO] [1692153315.771306881] [usb_cam]: This devices supproted formats:
[INFO] [1692153315.771485598] [usb_cam]: 	Motion-JPEG: 1920 x 1080 (30 Hz)
[INFO] [1692153315.771499280] [usb_cam]: 	Motion-JPEG: 1280 x 720 (30 Hz)
[INFO] [1692153315.771507354] [usb_cam]: 	Motion-JPEG: 640 x 480 (30 Hz)
[INFO] [1692153315.771514989] [usb_cam]: 	Motion-JPEG: 320 x 240 (30 Hz)
[INFO] [1692153315.771523124] [usb_cam]: Setting 'white_balance' to 4000
unknown control 'white_balance_temperature_auto'

unknown control 'white_balance_temperature'

[INFO] [1692153315.802487255] [usb_cam]: Setting 'exposure_auto' to 1
[INFO] [1692153315.802531818] [usb_cam]: Setting 'exposure' to 100
unknown control 'exposure_auto'

unknown control 'exposure_absolute'

[INFO] [1692153315.831822932] [usb_cam]: Setting 'focus_auto' to 0
unknown control 'focus_auto'

[INFO] [1692153315.853677597] [usb_cam]: Timer triggering every 33 ms
free(): invalid pointer
[ros2run]: Aborted
```

**params_2.yaml**
```
/**:
    ros__parameters:
      video_device: "/dev/video2"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "camera2"
      pixel_format: "mjpeg2rgb"  # see usb_cam/supported_formats for list of supported formats
      image_width: 640
      image_height: 480
      camera_name: "usb_cam"
      # reusing same camera intrinsics only for demo, should really be unique for camera2"
      camera_info_url: "package://usb_cam/config/camera_info.yaml"
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
      auto_white_balance: false
      white_balance: 4000
      autoexposure: false
      exposure: 100
      autofocus: false
      focus: -1
```

### Tested options
1. switching different `io_method`, no difference
2. switching different `pixel_format` (although it only states MJPEG), switch to `yuyv` could start the camera, but the image is half black and half white noise.

### v4l2-compliance test

```
$ v4l2-compliance -d /dev/video2
v4l2-compliance 1.22.1, 64 bits, 64-bit time_t

Compliance test for uvcvideo device /dev/video2:

Driver Info:
	Driver name      : uvcvideo
	Card type        : USB CAMERA 
	Bus info         : usb-0000:00:14.0-1
	Driver version   : 6.2.13
	Capabilities     : 0x84a00001
		Video Capture
		Metadata Capture
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps      : 0x04200001
		Video Capture
		Streaming
		Extended Pix Format
Media Driver Info:
	Driver name      : uvcvideo
	Model            : USB CAMERA 
	Serial           : 
	Bus info         : usb-0000:00:14.0-1
	Media version    : 6.2.13
	Hardware revision: 0x00000010 (16)
	Driver version   : 6.2.13
Interface Info:
	ID               : 0x03000002
	Type             : V4L Video
Entity Info:
	ID               : 0x00000001 (1)
	Name             : USB CAMERA 
	Function         : V4L2 I/O
	Flags            : default
	Pad 0x01000007   : 0: Sink
	  Link 0x02000013: from remote pad 0x100000a of entity 'Processing 4' (Video Pixel Formatter): Data, Enabled, Immutable

Required ioctls:
	test MC information (see 'Media Driver Info' above): OK
	test VIDIOC_QUERYCAP: OK
	test invalid ioctls: OK

Allow for multiple opens:
	test second /dev/video2 open: OK
	test VIDIOC_QUERYCAP: OK
	test VIDIOC_G/S_PRIORITY: OK
	test for unlimited opens: OK

Debug ioctls:
	test VIDIOC_DBG_G/S_REGISTER: OK (Not Supported)
	test VIDIOC_LOG_STATUS: OK (Not Supported)

Input ioctls:
	test VIDIOC_G/S_TUNER/ENUM_FREQ_BANDS: OK (Not Supported)
	test VIDIOC_G/S_FREQUENCY: OK (Not Supported)
	test VIDIOC_S_HW_FREQ_SEEK: OK (Not Supported)
	test VIDIOC_ENUMAUDIO: OK (Not Supported)
	test VIDIOC_G/S/ENUMINPUT: OK
	test VIDIOC_G/S_AUDIO: OK (Not Supported)
	Inputs: 1 Audio Inputs: 0 Tuners: 0

Output ioctls:
	test VIDIOC_G/S_MODULATOR: OK (Not Supported)
	test VIDIOC_G/S_FREQUENCY: OK (Not Supported)
	test VIDIOC_ENUMAUDOUT: OK (Not Supported)
	test VIDIOC_G/S/ENUMOUTPUT: OK (Not Supported)
	test VIDIOC_G/S_AUDOUT: OK (Not Supported)
	Outputs: 0 Audio Outputs: 0 Modulators: 0

Input/Output configuration ioctls:
	test VIDIOC_ENUM/G/S/QUERY_STD: OK (Not Supported)
	test VIDIOC_ENUM/G/S/QUERY_DV_TIMINGS: OK (Not Supported)
	test VIDIOC_DV_TIMINGS_CAP: OK (Not Supported)
	test VIDIOC_G/S_EDID: OK (Not Supported)

Control ioctls (Input 0):
	test VIDIOC_QUERY_EXT_CTRL/QUERYMENU: OK
	test VIDIOC_QUERYCTRL: OK
	test VIDIOC_G/S_CTRL: OK
	test VIDIOC_G/S/TRY_EXT_CTRLS: OK
	test VIDIOC_(UN)SUBSCRIBE_EVENT/DQEVENT: OK (Not Supported)
	test VIDIOC_G/S_JPEGCOMP: OK (Not Supported)
	Standard Controls: 0 Private Controls: 0

Format ioctls (Input 0):
	test VIDIOC_ENUM_FMT/FRAMESIZES/FRAMEINTERVALS: OK
	test VIDIOC_G/S_PARM: OK
	test VIDIOC_G_FBUF: OK (Not Supported)
	test VIDIOC_G_FMT: OK
	test VIDIOC_TRY_FMT: OK
		warn: v4l2-test-formats.cpp(1036): Could not set fmt2
	test VIDIOC_S_FMT: OK
	test VIDIOC_G_SLICED_VBI_CAP: OK (Not Supported)
	test Cropping: OK (Not Supported)
	test Composing: OK (Not Supported)
	test Scaling: OK (Not Supported)

Codec ioctls (Input 0):
	test VIDIOC_(TRY_)ENCODER_CMD: OK (Not Supported)
	test VIDIOC_G_ENC_INDEX: OK (Not Supported)
	test VIDIOC_(TRY_)DECODER_CMD: OK (Not Supported)

Buffer ioctls (Input 0):
	test VIDIOC_REQBUFS/CREATE_BUFS/QUERYBUF: OK
	test VIDIOC_EXPBUF: OK
	test Requests: OK (Not Supported)

Total for uvcvideo device /dev/video2: 46, Succeeded: 46, Failed: 0, Warnings: 1
```

### LINKED ISSUE #277: cannot find demo_launch.py
I might miss something important... but I couldn't find any launch file named demo_launch.py

I am working on ros2 branch. I would be appreciate to anyone who could direct me to that file.

### PR DESCRIPTION
**Pull request by flynneva**
Closes #274 
Closes #275 
Closes #277

### CODE REVIEW

**Comment by TZECHIN6** [comment]
Screenshot from 2023-08-22 13-41-16

I have tested the fix, so far the camera can be launched for couple minutes and no crashing.

However as you can see from the image, the decoder seem not well functioning.... not sure is it caused by my hardware

**Comment by flynneva** [comment]
@TZECHIN6 is anything printed to the console?

I'll take a look at this again over the weekend but any more info you can give would help me track this down!

**Comment by TZECHIN6** [comment]
> @TZECHIN6 is anything printed to the console?
> 
> I'll take a look at this again over the weekend but any more info you can give would help me track this down!

Screenshot from 2023-08-25 15-51-03

Sadly the console looks normal... might be others could help check this with their own cable and camera?

**Comment by flynneva** [comment]
@TZECHIN6 could you possibly try one more time? For my MJPEG camera the image looks OK...so I am not quite sure what the issue for yours is.

If its still an issue for you - could you spin it out into another follow-up issue and we can tackle it with a separate PR.

**Pull request merged**
