### PR TITLE
Auto-generate matrix for CI

### PR DESCRIPTION
**Pull request by flynneva**
- [x] Adds CI support for ROS 2 Iron (by auto-generating CI matrix)
- [x] Ensure only active ROS distros are added to generated CI matrix
- [x] Also add ROS 1 CI job (noetic)
- [ ] Add basic ROS 1 node wrapper around base usb_cam library

Relates to #255

### CODE REVIEW

**Comment by flynneva** [comment]
@twdragon @knorth55 so this is just a rough draft for now...but you can see how this PR auto-generates the CI matrix for us (ideally for just the active ROS distros.) for both ROS 1 and ROS 2.

Tomorrow I'll add a commit that creates a basic ROS 1 node wrapper we can use as a starting point...so we all can then use the same base library for both ROS 1 and ROS 2.

Let me know if you have any questions so far 👍🏼

**Comment by flynneva** [comment]
@twdragon @knorth55 so how much of the first ROS 1 node did you guys want me to add here? I figured I would just get it "stood up" and then you guys update it in other PRs.

Is that OK with you guys? If yes, then this PR is ready to be merged (I am OK with having the ROS 1 CI job fail for a while while we work on getting it up and running.

**Comment by twdragon** [comment]
@flynneva thanks for this contribution! Let me study a bit the code to see what should be done to match with the new internal API. I think it could be done

**Comment by flynneva** [comment]
@twdragon any updates here? Let me know if you have any questions

**Comment by twdragon** [comment]
@flynneva unfortunately no, I have a lot of tasks for now. But I will not
leave the project, do not worry. I hope to return to it in the middle of
August, after solving some of my tasks emerged now

сб, 15 июл. 2023 г., 18:20 Evan Flynn ***@***.***>:

**Comment by flynneva** [comment]
Superseeded by #294

**Pull request closed without merging**
