### PR TITLE
fix memory leak in usb_cam.cpp

### LINKED ISSUE #211: Memory leak in develop branch, in  UsbCam::mjpeg2rgb()
https://github.com/ros-drivers/usb_cam/blob/develop/src/usb_cam.cpp line# 501

Calling both `av_new_packet() `and `av_packet_from_data()` allocates the buffer within `avpkt.buf` twice, causing usb_cam to run out of memory.

Possible solution: call `av_init_packet(&avpkt)` instead of `av_new_packet(&avpkt, len)`  which does not initialize this buffer, then call `av_packet_from_data()` which does.

Not making a pull request, since this is in process of refactoring anyway.

### PR DESCRIPTION
**Pull request by knorth55**
we should do step by step, not making a big PR.
also this is not a refactoring, but a issue solution.
the priority is higher than refactoring.

with this PR, the memory leaks disappear.
closes #211 

https://user-images.githubusercontent.com/9300063/222413841-5e0ac1d6-9818-40d2-8089-7c96ffd85378.mp4

### CODE REVIEW

**Comment by knorth55** [comment]
@twdragon can you check this PR and check there is no memory leak?

**Comment by twdragon** [comment]
> @twdragon can you check this PR and check there is no memory leak? I will work on #231 ofcourse, but this PR should be merged first.
> 
> I also think we should release the new version after merging this PR and before merging #231. #231 may cause some errors, so between merging #231 and next-next release, we should take time for issue reporting by source-build users.

@knorth55 sure! This is what I am doing right now l. I also compare variants with used avcodec functions to ensure that there are no memory leaks.

I agree to release the version with this PR merged in case there are no serious errors, also because now there is no need for end user to change configuration

**Comment by knorth55** [comment]
@twdragon thank you! please test this PR and merge this if there is no more memory leaks.

after this PR is merged, I will move forward for the releasing this package.

**Comment by twdragon** [comment]
@knorth55 I thoroughly check the presence of memory leaks in comparison tests with and without the application of your PR. Let me please enumerate the results here:
- I forgot to use `av_init_packet()` when preparing my PR #221, so thank you very much for the notification;
- I compared the amount of allocated memory with and without `av_init_packet()`. It appeared only when `mjpeg` or `h264` pixel format was activated but always when `av_init_packet()` is not used.
- The amount of leaking memory depends strangely on the version of FFMPEG which was in use. I tested `4.4.2` from apt and bleeding-edge `N-108445-ga1bfb5290e`. When the bleeding-edge version is used the leak is weaker, and the memory amount oscillates, but it is still present. On the stable version, the amount of allocated memory grows linearly.

After this test, I think. I can merge this PR. I will do it in a couple of hours! Thank you again!

**Pull request merged**
