### PR TITLE
add myself as a maintainer for ros2

### PR DESCRIPTION
**Pull request by flynneva**

### CODE REVIEW

**Comment by flynneva** [comment]
@k-okada @rctoris @karsten1987 ready for review i think

**Review by Karsten1987 — APPROVED** [review]
thanks!

**Comment by flynneva** [comment]
@Karsten1987 since this repo is orphaned.....who can actually merge this PR and add me as an owner to the repo?

**Comment by wjwwood** [comment]
@flynneva I added you to a team with access to this repository. Once you accept you can merge yourself in.

**Comment by tfoote** [comment]
As you're planning to pick up maintainership I would suggest that you remove the old maintainers at the same time to make it clear.

**Comment by flynneva** [comment]
going to go ahead and merge this since the changes were already approved before

**Pull request merged**
